package ws

type WsDepthResponse struct {
	Type    string `json:"type"`
	Channel string `json:"channel"`
	Content struct {
		Channel  string `json:"channel"`
		DataType string `json:"dataType"`
		Data     []struct {
			StartVersion string `json:"startVersion"`
			EndVersion   string `json:"endVersion"`
			Level        int    `json:"level"`
			ContractId   string `json:"contractId"`
			ContractName string `json:"contractName"`
			Asks         []struct {
				Price string `json:"price"`
				Size  string `json:"size"`
			} `json:"asks"`
			Bids []struct {
				Price string `json:"price"`
				Size  string `json:"size"`
			} `json:"bids"`
			DepthType string `json:"depthType"`
		} `json:"data"`
	} `json:"content"`
}

type WsPrivateResponse struct {
	Type    string `json:"type"`
	Content struct {
		Event   string `json:"event"`
		Version int    `json:"version"`
		Data    struct {
			Account    []interface{} `json:"account"`
			Collateral []struct {
				UserId                 string `json:"userId"`
				AccountId              string `json:"accountId"`
				CoinId                 string `json:"coinId"`
				Amount                 string `json:"amount"`
				LegacyAmount           string `json:"legacyAmount"`
				CumDepositAmount       string `json:"cumDepositAmount"`
				CumWithdrawAmount      string `json:"cumWithdrawAmount"`
				CumTransferInAmount    string `json:"cumTransferInAmount"`
				CumTransferOutAmount   string `json:"cumTransferOutAmount"`
				CumPositionBuyAmount   string `json:"cumPositionBuyAmount"`
				CumPositionSellAmount  string `json:"cumPositionSellAmount"`
				CumFillFeeAmount       string `json:"cumFillFeeAmount"`
				CumFundingFeeAmount    string `json:"cumFundingFeeAmount"`
				CumFillFeeIncomeAmount string `json:"cumFillFeeIncomeAmount"`
				CreatedTime            string `json:"createdTime"`
				UpdatedTime            string `json:"updatedTime"`
			} `json:"collateral"`
			CollateralTransaction []struct {
				Id                     string `json:"id"`
				UserId                 string `json:"userId"`
				AccountId              string `json:"accountId"`
				CoinId                 string `json:"coinId"`
				Type                   string `json:"type"`
				DeltaAmount            string `json:"deltaAmount"`
				DeltaLegacyAmount      string `json:"deltaLegacyAmount"`
				BeforeAmount           string `json:"beforeAmount"`
				BeforeLegacyAmount     string `json:"beforeLegacyAmount"`
				FillCloseSize          string `json:"fillCloseSize"`
				FillCloseValue         string `json:"fillCloseValue"`
				FillCloseFee           string `json:"fillCloseFee"`
				FillOpenSize           string `json:"fillOpenSize"`
				FillOpenValue          string `json:"fillOpenValue"`
				FillOpenFee            string `json:"fillOpenFee"`
				FillPrice              string `json:"fillPrice"`
				LiquidateFee           string `json:"liquidateFee"`
				RealizePnl             string `json:"realizePnl"`
				IsLiquidate            bool   `json:"isLiquidate"`
				IsDeleverage           bool   `json:"isDeleverage"`
				FundingTime            string `json:"fundingTime"`
				FundingRate            string `json:"fundingRate"`
				FundingIndexPrice      string `json:"fundingIndexPrice"`
				FundingOraclePrice     string `json:"fundingOraclePrice"`
				FundingPositionSize    string `json:"fundingPositionSize"`
				DepositId              string `json:"depositId"`
				WithdrawId             string `json:"withdrawId"`
				TransferInId           string `json:"transferInId"`
				TransferOutId          string `json:"transferOutId"`
				TransferReason         string `json:"transferReason"`
				OrderId                string `json:"orderId"`
				OrderFillTransactionId string `json:"orderFillTransactionId"`
				OrderAccountId         string `json:"orderAccountId"`
				PositionContractId     string `json:"positionContractId"`
				PositionTransactionId  string `json:"positionTransactionId"`
				ForceWithdrawId        string `json:"forceWithdrawId"`
				ForceTradeId           string `json:"forceTradeId"`
				ExtraType              string `json:"extraType"`
				ExtraDataJson          string `json:"extraDataJson"`
				CensorStatus           string `json:"censorStatus"`
				CensorTxId             string `json:"censorTxId"`
				CensorTime             string `json:"censorTime"`
				CensorFailCode         string `json:"censorFailCode"`
				CensorFailReason       string `json:"censorFailReason"`
				L2TxId                 string `json:"l2TxId"`
				L2RejectTime           string `json:"l2RejectTime"`
				L2RejectCode           string `json:"l2RejectCode"`
				L2RejectReason         string `json:"l2RejectReason"`
				L2ApprovedTime         string `json:"l2ApprovedTime"`
				CreatedTime            string `json:"createdTime"`
				UpdatedTime            string `json:"updatedTime"`
			} `json:"collateralTransaction"`
			Position []struct {
				UserId        string `json:"userId"`
				AccountId     string `json:"accountId"`
				CoinId        string `json:"coinId"`
				ContractId    string `json:"contractId"`
				OpenSize      string `json:"openSize"`
				OpenValue     string `json:"openValue"`
				OpenFee       string `json:"openFee"`
				FundingFee    string `json:"fundingFee"`
				LongTermCount int    `json:"longTermCount"`
				LongTermStat  struct {
					CumOpenSize     string `json:"cumOpenSize"`
					CumOpenValue    string `json:"cumOpenValue"`
					CumOpenFee      string `json:"cumOpenFee"`
					CumCloseSize    string `json:"cumCloseSize"`
					CumCloseValue   string `json:"cumCloseValue"`
					CumCloseFee     string `json:"cumCloseFee"`
					CumFundingFee   string `json:"cumFundingFee"`
					CumLiquidateFee string `json:"cumLiquidateFee"`
				} `json:"longTermStat"`
				LongTermCreatedTime string `json:"longTermCreatedTime"`
				LongTermUpdatedTime string `json:"longTermUpdatedTime"`
				ShortTermCount      int    `json:"shortTermCount"`
				ShortTermStat       struct {
					CumOpenSize     string `json:"cumOpenSize"`
					CumOpenValue    string `json:"cumOpenValue"`
					CumOpenFee      string `json:"cumOpenFee"`
					CumCloseSize    string `json:"cumCloseSize"`
					CumCloseValue   string `json:"cumCloseValue"`
					CumCloseFee     string `json:"cumCloseFee"`
					CumFundingFee   string `json:"cumFundingFee"`
					CumLiquidateFee string `json:"cumLiquidateFee"`
				} `json:"shortTermStat"`
				ShortTermCreatedTime string `json:"shortTermCreatedTime"`
				ShortTermUpdatedTime string `json:"shortTermUpdatedTime"`
				LongTotalStat        struct {
					CumOpenSize     string `json:"cumOpenSize"`
					CumOpenValue    string `json:"cumOpenValue"`
					CumOpenFee      string `json:"cumOpenFee"`
					CumCloseSize    string `json:"cumCloseSize"`
					CumCloseValue   string `json:"cumCloseValue"`
					CumCloseFee     string `json:"cumCloseFee"`
					CumFundingFee   string `json:"cumFundingFee"`
					CumLiquidateFee string `json:"cumLiquidateFee"`
				} `json:"longTotalStat"`
				ShortTotalStat struct {
					CumOpenSize     string `json:"cumOpenSize"`
					CumOpenValue    string `json:"cumOpenValue"`
					CumOpenFee      string `json:"cumOpenFee"`
					CumCloseSize    string `json:"cumCloseSize"`
					CumCloseValue   string `json:"cumCloseValue"`
					CumCloseFee     string `json:"cumCloseFee"`
					CumFundingFee   string `json:"cumFundingFee"`
					CumLiquidateFee string `json:"cumLiquidateFee"`
				} `json:"shortTotalStat"`
				CreatedTime string `json:"createdTime"`
				UpdatedTime string `json:"updatedTime"`
			} `json:"position"`
			PositionTransaction []struct {
				Id                      string `json:"id"`
				UserId                  string `json:"userId"`
				AccountId               string `json:"accountId"`
				CoinId                  string `json:"coinId"`
				ContractId              string `json:"contractId"`
				Type                    string `json:"type"`
				DeltaOpenSize           string `json:"deltaOpenSize"`
				DeltaOpenValue          string `json:"deltaOpenValue"`
				DeltaOpenFee            string `json:"deltaOpenFee"`
				DeltaFundingFee         string `json:"deltaFundingFee"`
				BeforeOpenSize          string `json:"beforeOpenSize"`
				BeforeOpenValue         string `json:"beforeOpenValue"`
				BeforeOpenFee           string `json:"beforeOpenFee"`
				BeforeFundingFee        string `json:"beforeFundingFee"`
				FillCloseSize           string `json:"fillCloseSize"`
				FillCloseValue          string `json:"fillCloseValue"`
				FillCloseFee            string `json:"fillCloseFee"`
				FillOpenSize            string `json:"fillOpenSize"`
				FillOpenValue           string `json:"fillOpenValue"`
				FillOpenFee             string `json:"fillOpenFee"`
				FillPrice               string `json:"fillPrice"`
				LiquidateFee            string `json:"liquidateFee"`
				RealizePnl              string `json:"realizePnl"`
				IsLiquidate             bool   `json:"isLiquidate"`
				IsDeleverage            bool   `json:"isDeleverage"`
				FundingTime             string `json:"fundingTime"`
				FundingRate             string `json:"fundingRate"`
				FundingIndexPrice       string `json:"fundingIndexPrice"`
				FundingOraclePrice      string `json:"fundingOraclePrice"`
				FundingPositionSize     string `json:"fundingPositionSize"`
				OrderId                 string `json:"orderId"`
				OrderFillTransactionId  string `json:"orderFillTransactionId"`
				CollateralTransactionId string `json:"collateralTransactionId"`
				ForceTradeId            string `json:"forceTradeId"`
				ExtraType               string `json:"extraType"`
				ExtraDataJson           string `json:"extraDataJson"`
				CensorStatus            string `json:"censorStatus"`
				CensorTxId              string `json:"censorTxId"`
				CensorTime              string `json:"censorTime"`
				CensorFailCode          string `json:"censorFailCode"`
				CensorFailReason        string `json:"censorFailReason"`
				L2TxId                  string `json:"l2TxId"`
				L2RejectTime            string `json:"l2RejectTime"`
				L2RejectCode            string `json:"l2RejectCode"`
				L2RejectReason          string `json:"l2RejectReason"`
				L2ApprovedTime          string `json:"l2ApprovedTime"`
				CreatedTime             string `json:"createdTime"`
				UpdatedTime             string `json:"updatedTime"`
			} `json:"positionTransaction"`
			Deposit     []interface{} `json:"deposit"`
			Withdraw    []interface{} `json:"withdraw"`
			TransferIn  []interface{} `json:"transferIn"`
			TransferOut []interface{} `json:"transferOut"`
			Order       []struct {
				Id                    string `json:"id"`
				UserId                string `json:"userId"`
				AccountId             string `json:"accountId"`
				CoinId                string `json:"coinId"`
				ContractId            string `json:"contractId"`
				Side                  string `json:"side"`
				Price                 string `json:"price"`
				Size                  string `json:"size"`
				ClientOrderId         string `json:"clientOrderId"`
				Type                  string `json:"type"`
				TimeInForce           string `json:"timeInForce"`
				ReduceOnly            bool   `json:"reduceOnly"`
				TriggerPrice          string `json:"triggerPrice"`
				TriggerPriceType      string `json:"triggerPriceType"`
				ExpireTime            string `json:"expireTime"`
				SourceKey             string `json:"sourceKey"`
				IsPositionTpsl        bool   `json:"isPositionTpsl"`
				IsLiquidate           bool   `json:"isLiquidate"`
				IsDeleverage          bool   `json:"isDeleverage"`
				OpenTpslParentOrderId string `json:"openTpslParentOrderId"`
				IsSetOpenTp           bool   `json:"isSetOpenTp"`
				OpenTp                struct {
					Side             string `json:"side"`
					Price            string `json:"price"`
					Size             string `json:"size"`
					ClientOrderId    string `json:"clientOrderId"`
					TriggerPrice     string `json:"triggerPrice"`
					TriggerPriceType string `json:"triggerPriceType"`
					ExpireTime       string `json:"expireTime"`
					L2Nonce          string `json:"l2Nonce"`
					L2Value          string `json:"l2Value"`
					L2Size           string `json:"l2Size"`
					L2LimitFee       string `json:"l2LimitFee"`
					L2ExpireTime     string `json:"l2ExpireTime"`
					L2Signature      struct {
						R string `json:"r"`
						S string `json:"s"`
						V string `json:"v"`
					} `json:"l2Signature"`
				} `json:"openTp"`
				IsSetOpenSl bool `json:"isSetOpenSl"`
				OpenSl      struct {
					Side             string `json:"side"`
					Price            string `json:"price"`
					Size             string `json:"size"`
					ClientOrderId    string `json:"clientOrderId"`
					TriggerPrice     string `json:"triggerPrice"`
					TriggerPriceType string `json:"triggerPriceType"`
					ExpireTime       string `json:"expireTime"`
					L2Nonce          string `json:"l2Nonce"`
					L2Value          string `json:"l2Value"`
					L2Size           string `json:"l2Size"`
					L2LimitFee       string `json:"l2LimitFee"`
					L2ExpireTime     string `json:"l2ExpireTime"`
					L2Signature      struct {
						R string `json:"r"`
						S string `json:"s"`
						V string `json:"v"`
					} `json:"l2Signature"`
				} `json:"openSl"`
				IsWithoutMatch            bool   `json:"isWithoutMatch"`
				WithoutMatchFillSize      string `json:"withoutMatchFillSize"`
				WithoutMatchFillValue     string `json:"withoutMatchFillValue"`
				WithoutMatchPeerAccountId string `json:"withoutMatchPeerAccountId"`
				WithoutMatchPeerOrderId   string `json:"withoutMatchPeerOrderId"`
				MaxLeverage               string `json:"maxLeverage"`
				TakerFeeRate              string `json:"takerFeeRate"`
				MakerFeeRate              string `json:"makerFeeRate"`
				LiquidateFeeRate          string `json:"liquidateFeeRate"`
				MarketLimitPrice          string `json:"marketLimitPrice"`
				MarketLimitValue          string `json:"marketLimitValue"`
				L2Nonce                   string `json:"l2Nonce"`
				L2Value                   string `json:"l2Value"`
				L2Size                    string `json:"l2Size"`
				L2LimitFee                string `json:"l2LimitFee"`
				L2ExpireTime              string `json:"l2ExpireTime"`
				L2Signature               struct {
					R string `json:"r"`
					S string `json:"s"`
					V string `json:"v"`
				} `json:"l2Signature"`
				ExtraType         string `json:"extraType"`
				ExtraDataJson     string `json:"extraDataJson"`
				Status            string `json:"status"`
				MatchSequenceId   string `json:"matchSequenceId"`
				TriggerTime       string `json:"triggerTime"`
				TriggerPriceTime  string `json:"triggerPriceTime"`
				TriggerPriceValue string `json:"triggerPriceValue"`
				CancelReason      string `json:"cancelReason"`
				CumFillSize       string `json:"cumFillSize"`
				CumFillValue      string `json:"cumFillValue"`
				CumFillFee        string `json:"cumFillFee"`
				MaxFillPrice      string `json:"maxFillPrice"`
				MinFillPrice      string `json:"minFillPrice"`
				CumLiquidateFee   string `json:"cumLiquidateFee"`
				CumRealizePnl     string `json:"cumRealizePnl"`
				CumMatchSize      string `json:"cumMatchSize"`
				CumMatchValue     string `json:"cumMatchValue"`
				CumMatchFee       string `json:"cumMatchFee"`
				CumFailSize       string `json:"cumFailSize"`
				CumFailValue      string `json:"cumFailValue"`
				CumFailFee        string `json:"cumFailFee"`
				CumApprovedSize   string `json:"cumApprovedSize"`
				CumApprovedValue  string `json:"cumApprovedValue"`
				CumApprovedFee    string `json:"cumApprovedFee"`
				CreatedTime       string `json:"createdTime"`
				UpdatedTime       string `json:"updatedTime"`
			} `json:"order"`
			OrderFillTransaction []struct {
				Id                      string `json:"id"`
				UserId                  string `json:"userId"`
				AccountId               string `json:"accountId"`
				CoinId                  string `json:"coinId"`
				ContractId              string `json:"contractId"`
				OrderId                 string `json:"orderId"`
				OrderSide               string `json:"orderSide"`
				FillSize                string `json:"fillSize"`
				FillValue               string `json:"fillValue"`
				FillFee                 string `json:"fillFee"`
				FillPrice               string `json:"fillPrice"`
				LiquidateFee            string `json:"liquidateFee"`
				RealizePnl              string `json:"realizePnl"`
				Direction               string `json:"direction"`
				IsPositionTpsl          bool   `json:"isPositionTpsl"`
				IsLiquidate             bool   `json:"isLiquidate"`
				IsDeleverage            bool   `json:"isDeleverage"`
				IsWithoutMatch          bool   `json:"isWithoutMatch"`
				MatchSequenceId         string `json:"matchSequenceId"`
				MatchIndex              int    `json:"matchIndex"`
				MatchTime               string `json:"matchTime"`
				MatchAccountId          string `json:"matchAccountId"`
				MatchOrderId            string `json:"matchOrderId"`
				MatchFillId             string `json:"matchFillId"`
				PositionTransactionId   string `json:"positionTransactionId"`
				CollateralTransactionId string `json:"collateralTransactionId"`
				ExtraType               string `json:"extraType"`
				ExtraDataJson           string `json:"extraDataJson"`
				CensorStatus            string `json:"censorStatus"`
				CensorTxId              string `json:"censorTxId"`
				CensorTime              string `json:"censorTime"`
				CensorFailCode          string `json:"censorFailCode"`
				CensorFailReason        string `json:"censorFailReason"`
				L2TxId                  string `json:"l2TxId"`
				L2RejectTime            string `json:"l2RejectTime"`
				L2RejectCode            string `json:"l2RejectCode"`
				L2RejectReason          string `json:"l2RejectReason"`
				L2ApprovedTime          string `json:"l2ApprovedTime"`
				CreatedTime             string `json:"createdTime"`
				UpdatedTime             string `json:"updatedTime"`
			} `json:"orderFillTransaction"`
			ForceWithdrawList []interface{} `json:"forceWithdrawList"`
			ForceTradeList    []interface{} `json:"forceTradeList"`
			OraclePriceList   []interface{} `json:"oraclePriceList"`
			PositionTermList  []struct {
				UserId          string `json:"userId"`
				AccountId       string `json:"accountId"`
				CoinId          string `json:"coinId"`
				ContractId      string `json:"contractId"`
				TermCount       int    `json:"termCount"`
				CumOpenSize     string `json:"cumOpenSize"`
				CumOpenValue    string `json:"cumOpenValue"`
				CumOpenFee      string `json:"cumOpenFee"`
				CumCloseSize    string `json:"cumCloseSize"`
				CumCloseValue   string `json:"cumCloseValue"`
				CumCloseFee     string `json:"cumCloseFee"`
				CumFundingFee   string `json:"cumFundingFee"`
				CumLiquidateFee string `json:"cumLiquidateFee"`
				CreatedTime     string `json:"createdTime"`
				UpdatedTime     string `json:"updatedTime"`
				CurrentLeverage string `json:"currentLeverage"`
			} `json:"positionTermList"`
		} `json:"data"`
		Time      int64 `json:"time"`
		AccountId int   `json:"accountId"`
	} `json:"content"`
}
